version: 2.1
orbs:
  node: circleci/node@5.0.2
references:
  tag_filter: &tag_filter
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v\d+\.\d+\.\d+$/
jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access public
      - run:
          name: Publish Release on GitHub
          command: |
            ios_version=$(sed -n "/s.dependency 'Movement', '= [0-9].[0-9].[0-9]'/p" movement-sdk-react-native.podspec | sed "s/  s.dependency 'Movement', '= \([0-9].[0-9].[0-9]\)'/\1/")
            android_version=$(sed -n "/implementation 'com.foursquare:movementsdk:[0-9].[0-9].[0-9]'/p" android/build.gradle | sed "s/    implementation 'com.foursquare:movementsdk:\([0-9].[0-9].[0-9]\)'/\1/")
            curl -s -X POST -d "{\"tag_name\":\"$CIRCLE_TAG\",\"name\":\"$CIRCLE_TAG\",\"body\":\"iOS SDK version: ${ios_version}\nAndroid SDK version: ${android_version}\",\"draft\":false,\"prerelease\":false}" -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/foursquare/movement-sdk-react-native/releases"
workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
  tagged-build:
    jobs:
      - lint:
          <<: *tag_filter
      - deploy:
          requires:
            - lint
          <<: *tag_filter
